# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iamopstest(stagging)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iamopstesting.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b5aea4aa365f4bb1b884057d447125ad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a529ac72c0f54a1695bca965fa7e9489 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iamopstesting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5aea4aa365f4bb1b884057d447125ad }}/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stagging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iamopstest'
        slot-name: 'stagging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c69eac0cd53c4f6d927615348403fa7a }}
        images: 'iamopstesting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5aea4aa365f4bb1b884057d447125ad }}/latest:${{ github.sha }}'